// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, user_id, action, resource_type, resource_id, metadata, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
`

type CreateAuditLogParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Action       string
	ResourceType string
	ResourceID   pgtype.Text
	Metadata     []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
	)
	return err
}

const listAuditLogsForAdmin = `-- name: ListAuditLogsForAdmin :many
SELECT id, user_id, action, resource_type, resource_id, metadata, created_at
FROM audit_logs
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsForAdmin(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
