// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditTransaction = `-- name: CreateCreditTransaction :one
INSERT INTO credit_transactions (id, user_id, type, amount, balance_after, reference_type, reference_id, idempotency_key, description, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
RETURNING id, user_id, type, amount, balance_after, reference_type, reference_id, idempotency_key, description, created_at
`

type CreateCreditTransactionParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Type           string
	Amount         int32
	BalanceAfter   int32
	ReferenceType  pgtype.Text
	ReferenceID    pgtype.UUID
	IdempotencyKey pgtype.Text
	Description    pgtype.Text
}

func (q *Queries) CreateCreditTransaction(ctx context.Context, arg CreateCreditTransactionParams) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, createCreditTransaction,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.IdempotencyKey,
		arg.Description,
	)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const findCreditTransactionByIdempotencyKey = `-- name: FindCreditTransactionByIdempotencyKey :one
SELECT id, user_id, type, amount, balance_after, reference_type, reference_id, idempotency_key, description, created_at
FROM credit_transactions
WHERE user_id = $1 AND idempotency_key = $2
`

type FindCreditTransactionByIdempotencyKeyParams struct {
	UserID         pgtype.UUID
	IdempotencyKey pgtype.Text
}

func (q *Queries) FindCreditTransactionByIdempotencyKey(ctx context.Context, arg FindCreditTransactionByIdempotencyKeyParams) (CreditTransaction, error) {
	row := q.db.QueryRow(ctx, findCreditTransactionByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i CreditTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT user_id, balance, updated_at
FROM credit_wallets
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetWalletForUpdate(ctx context.Context, userID pgtype.UUID) (CreditWallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, userID)
	var i CreditWallet
	err := row.Scan(&i.UserID, &i.Balance, &i.UpdatedAt)
	return i, err
}

const listCreditTransactionsByUser = `-- name: ListCreditTransactionsByUser :many
SELECT id, user_id, type, amount, balance_after, reference_type, reference_id, idempotency_key, description, created_at
FROM credit_transactions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCreditTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]CreditTransaction, error) {
	rows, err := q.db.Query(ctx, listCreditTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditTransaction
	for rows.Next() {
		var i CreditTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.IdempotencyKey,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWallet = `-- name: UpsertWallet :exec
INSERT INTO credit_wallets (user_id, balance, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id)
DO UPDATE SET balance = EXCLUDED.balance, updated_at = now()
`

type UpsertWalletParams struct {
	UserID  pgtype.UUID
	Balance int32
}

func (q *Queries) UpsertWallet(ctx context.Context, arg UpsertWalletParams) error {
	_, err := q.db.Exec(ctx, upsertWallet, arg.UserID, arg.Balance)
	return err
}
