// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, domain, page_type, component_hint, tier, description
FROM templates
ORDER BY name ASC
`

type ListTemplatesRow struct {
	ID            string
	Name          string
	Domain        string
	PageType      string
	ComponentHint int32
	Tier          string
	Description   string
}

func (q *Queries) ListTemplates(ctx context.Context) ([]ListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTemplatesRow
	for rows.Next() {
		var i ListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.PageType,
			&i.ComponentHint,
			&i.Tier,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThemes = `-- name: ListThemes :many
SELECT slug, name, accent
FROM themes
ORDER BY name ASC
`

type ListThemesRow struct {
	Slug   string
	Name   string
	Accent string
}

func (q *Queries) ListThemes(ctx context.Context) ([]ListThemesRow, error) {
	rows, err := q.db.Query(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThemesRow
	for rows.Next() {
		var i ListThemesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Accent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
