// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: idempotency_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (id, user_id, operation, request_key, resource_type, resource_id, response_json, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), $8)
RETURNING id, user_id, operation, request_key, resource_type, resource_id, response_json, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Operation    string
	RequestKey   string
	ResourceType string
	ResourceID   pgtype.Text
	ResponseJson []byte
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.ID,
		arg.UserID,
		arg.Operation,
		arg.RequestKey,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResponseJson,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Operation,
		&i.RequestKey,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, operation, request_key, resource_type, resource_id, response_json, created_at, expires_at
FROM idempotency_keys
WHERE user_id = $1 AND operation = $2 AND request_key = $3
`

type GetIdempotencyKeyParams struct {
	UserID     pgtype.UUID
	Operation  string
	RequestKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Operation, arg.RequestKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Operation,
		&i.RequestKey,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
