// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGenerationJob = `-- name: CreateGenerationJob :one
INSERT INTO generation_jobs (id, user_id, project_id, page_id, request_id, status, prompt, page_type, domain, theme_slug, output_mode, credit_cost, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now(), now())
RETURNING id, user_id, project_id, page_id, request_id, status, prompt, page_type, domain, theme_slug, output_mode, credit_cost, error_message, retry_count, started_at, finished_at, created_at, updated_at
`

type CreateGenerationJobParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ProjectID  pgtype.UUID
	PageID     pgtype.UUID
	RequestID  string
	Status     string
	Prompt     string
	PageType   string
	Domain     string
	ThemeSlug  string
	OutputMode string
	CreditCost int32
}

type CreateGenerationJobRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ProjectID    pgtype.UUID
	PageID       pgtype.UUID
	RequestID    string
	Status       string
	Prompt       string
	PageType     string
	Domain       string
	ThemeSlug    string
	OutputMode   string
	CreditCost   int32
	ErrorMessage pgtype.Text
	RetryCount   int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateGenerationJob(ctx context.Context, arg CreateGenerationJobParams) (CreateGenerationJobRow, error) {
	row := q.db.QueryRow(ctx, createGenerationJob,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.PageID,
		arg.RequestID,
		arg.Status,
		arg.Prompt,
		arg.PageType,
		arg.Domain,
		arg.ThemeSlug,
		arg.OutputMode,
		arg.CreditCost,
	)
	var i CreateGenerationJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.PageID,
		&i.RequestID,
		&i.Status,
		&i.Prompt,
		&i.PageType,
		&i.Domain,
		&i.ThemeSlug,
		&i.OutputMode,
		&i.CreditCost,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedGenerationJob = `-- name: GetOwnedGenerationJob :one
SELECT id, user_id, project_id, page_id, request_id, status, prompt, page_type, domain, theme_slug, output_mode, credit_cost, error_message, retry_count, started_at, finished_at, created_at, updated_at
FROM generation_jobs
WHERE id = $1 AND user_id = $2
`

type GetOwnedGenerationJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetOwnedGenerationJobRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ProjectID    pgtype.UUID
	PageID       pgtype.UUID
	RequestID    string
	Status       string
	Prompt       string
	PageType     string
	Domain       string
	ThemeSlug    string
	OutputMode   string
	CreditCost   int32
	ErrorMessage pgtype.Text
	RetryCount   int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetOwnedGenerationJob(ctx context.Context, arg GetOwnedGenerationJobParams) (GetOwnedGenerationJobRow, error) {
	row := q.db.QueryRow(ctx, getOwnedGenerationJob, arg.ID, arg.UserID)
	var i GetOwnedGenerationJobRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.PageID,
		&i.RequestID,
		&i.Status,
		&i.Prompt,
		&i.PageType,
		&i.Domain,
		&i.ThemeSlug,
		&i.OutputMode,
		&i.CreditCost,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGenerationJobsForAdmin = `-- name: ListGenerationJobsForAdmin :many
SELECT id, user_id, project_id, page_id, request_id, status, prompt, page_type, domain, theme_slug, output_mode, credit_cost, error_message, retry_count, started_at, finished_at, created_at, updated_at
FROM generation_jobs
ORDER BY created_at DESC
`

type ListGenerationJobsForAdminRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	ProjectID    pgtype.UUID
	PageID       pgtype.UUID
	RequestID    string
	Status       string
	Prompt       string
	PageType     string
	Domain       string
	ThemeSlug    string
	OutputMode   string
	CreditCost   int32
	ErrorMessage pgtype.Text
	RetryCount   int32
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListGenerationJobsForAdmin(ctx context.Context) ([]ListGenerationJobsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listGenerationJobsForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGenerationJobsForAdminRow
	for rows.Next() {
		var i ListGenerationJobsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.PageID,
			&i.RequestID,
			&i.Status,
			&i.Prompt,
			&i.PageType,
			&i.Domain,
			&i.ThemeSlug,
			&i.OutputMode,
			&i.CreditCost,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenerationJobStatus = `-- name: UpdateGenerationJobStatus :exec
UPDATE generation_jobs
SET status = $2, error_message = $3, updated_at = now(), finished_at = CASE WHEN $2 IN ('succeeded', 'failed', 'refunded', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateGenerationJobStatusParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateGenerationJobStatus(ctx context.Context, arg UpdateGenerationJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateGenerationJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
