// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO project_pages (id, project_id, name, slug, page_type, created_at, updated_at)
SELECT $1, p.id, $3, $4, $5, now(), now()
FROM projects p
WHERE p.id = $2 AND p.user_id = $6 AND p.deleted_at IS NULL
RETURNING id, project_id, name, slug, page_type, current_version_id, created_at, updated_at
`

type CreatePageParams struct {
	ID       pgtype.UUID
	ID_2     pgtype.UUID
	Name     string
	Slug     string
	PageType string
	UserID   pgtype.UUID
}

type CreatePageRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Name             string
	Slug             string
	PageType         string
	CurrentVersionID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.ID,
		arg.ID_2,
		arg.Name,
		arg.Slug,
		arg.PageType,
		arg.UserID,
	)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PageType,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedPage = `-- name: GetOwnedPage :one
SELECT pp.id, pp.project_id, pp.name, pp.slug, pp.page_type, pp.current_version_id, pp.created_at, pp.updated_at
FROM project_pages pp
JOIN projects p ON p.id = pp.project_id
WHERE pp.id = $1 AND p.user_id = $2 AND pp.deleted_at IS NULL AND p.deleted_at IS NULL
`

type GetOwnedPageParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetOwnedPageRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Name             string
	Slug             string
	PageType         string
	CurrentVersionID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetOwnedPage(ctx context.Context, arg GetOwnedPageParams) (GetOwnedPageRow, error) {
	row := q.db.QueryRow(ctx, getOwnedPage, arg.ID, arg.UserID)
	var i GetOwnedPageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PageType,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnedProjectPages = `-- name: ListOwnedProjectPages :many
SELECT pp.id, pp.project_id, pp.name, pp.slug, pp.page_type, pp.current_version_id, pp.created_at, pp.updated_at
FROM project_pages pp
JOIN projects p ON p.id = pp.project_id
WHERE pp.project_id = $1 AND p.user_id = $2 AND pp.deleted_at IS NULL AND p.deleted_at IS NULL
ORDER BY pp.created_at ASC
`

type ListOwnedProjectPagesParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

type ListOwnedProjectPagesRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Name             string
	Slug             string
	PageType         string
	CurrentVersionID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListOwnedProjectPages(ctx context.Context, arg ListOwnedProjectPagesParams) ([]ListOwnedProjectPagesRow, error) {
	rows, err := q.db.Query(ctx, listOwnedProjectPages, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedProjectPagesRow
	for rows.Next() {
		var i ListOwnedProjectPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.PageType,
			&i.CurrentVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE project_pages pp
SET current_version_id = $1, updated_at = now()
FROM projects p
WHERE pp.id = $2 AND pp.project_id = p.id AND p.user_id = $3
`

type SetCurrentVersionParams struct {
	CurrentVersionID pgtype.UUID
	ID               pgtype.UUID
	UserID           pgtype.UUID
}

func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.CurrentVersionID, arg.ID, arg.UserID)
	return err
}

const softDeleteOwnedPage = `-- name: SoftDeleteOwnedPage :exec
UPDATE project_pages pp
SET deleted_at = now(), updated_at = now()
FROM projects p
WHERE pp.id = $1 AND pp.project_id = p.id AND p.user_id = $2 AND pp.deleted_at IS NULL
`

type SoftDeleteOwnedPageParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteOwnedPage(ctx context.Context, arg SoftDeleteOwnedPageParams) error {
	_, err := q.db.Exec(ctx, softDeleteOwnedPage, arg.ID, arg.UserID)
	return err
}

const updateOwnedPage = `-- name: UpdateOwnedPage :one
UPDATE project_pages pp
SET name = $3, slug = $4, page_type = $5, updated_at = now()
FROM projects p
WHERE pp.id = $1 AND pp.project_id = p.id AND p.user_id = $2 AND pp.deleted_at IS NULL
RETURNING pp.id, pp.project_id, pp.name, pp.slug, pp.page_type, pp.current_version_id, pp.created_at, pp.updated_at
`

type UpdateOwnedPageParams struct {
	ID       pgtype.UUID
	UserID   pgtype.UUID
	Name     string
	Slug     string
	PageType string
}

type UpdateOwnedPageRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Name             string
	Slug             string
	PageType         string
	CurrentVersionID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateOwnedPage(ctx context.Context, arg UpdateOwnedPageParams) (UpdateOwnedPageRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedPage,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.PageType,
	)
	var i UpdateOwnedPageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.PageType,
		&i.CurrentVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
