// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, name, description, default_theme_slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, user_id, name, description, default_theme_slug, created_at, updated_at
`

type CreateProjectParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
}

type CreateProjectRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.DefaultThemeSlug,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultThemeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedProject = `-- name: GetOwnedProject :one
SELECT id, user_id, name, description, default_theme_slug, created_at, updated_at
FROM projects
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetOwnedProjectParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetOwnedProjectRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetOwnedProject(ctx context.Context, arg GetOwnedProjectParams) (GetOwnedProjectRow, error) {
	row := q.db.QueryRow(ctx, getOwnedProject, arg.ID, arg.UserID)
	var i GetOwnedProjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultThemeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT id, user_id, name, description, default_theme_slug, created_at, updated_at
FROM projects
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListProjectsByUserRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListProjectsByUser(ctx context.Context, userID pgtype.UUID) ([]ListProjectsByUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsByUserRow
	for rows.Next() {
		var i ListProjectsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.DefaultThemeSlug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOwnedProject = `-- name: SoftDeleteOwnedProject :execrows
UPDATE projects
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteOwnedProjectParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteOwnedProject(ctx context.Context, arg SoftDeleteOwnedProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOwnedProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOwnedProject = `-- name: UpdateOwnedProject :one
UPDATE projects
SET name = $3, description = $4, default_theme_slug = $5, updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, description, default_theme_slug, created_at, updated_at
`

type UpdateOwnedProjectParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
}

type UpdateOwnedProjectRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Name             string
	Description      string
	DefaultThemeSlug string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateOwnedProject(ctx context.Context, arg UpdateOwnedProjectParams) (UpdateOwnedProjectRow, error) {
	row := q.db.QueryRow(ctx, updateOwnedProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.DefaultThemeSlug,
	)
	var i UpdateOwnedProjectRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.DefaultThemeSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
