// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPageVersion = `-- name: CreatePageVersion :one
INSERT INTO page_versions (id, page_id, version_number, prompt, schema_json, generated_code, quality_score, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now())
RETURNING id, page_id, version_number, prompt, schema_json, generated_code, quality_score, created_by, created_at
`

type CreatePageVersionParams struct {
	ID            pgtype.UUID
	PageID        pgtype.UUID
	VersionNumber int32
	Prompt        string
	SchemaJson    []byte
	GeneratedCode string
	QualityScore  pgtype.Numeric
	CreatedBy     pgtype.UUID
}

func (q *Queries) CreatePageVersion(ctx context.Context, arg CreatePageVersionParams) (PageVersion, error) {
	row := q.db.QueryRow(ctx, createPageVersion,
		arg.ID,
		arg.PageID,
		arg.VersionNumber,
		arg.Prompt,
		arg.SchemaJson,
		arg.GeneratedCode,
		arg.QualityScore,
		arg.CreatedBy,
	)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.Prompt,
		&i.SchemaJson,
		&i.GeneratedCode,
		&i.QualityScore,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOwnedPageVersion = `-- name: GetOwnedPageVersion :one
SELECT pv.id, pv.page_id, pv.version_number, pv.prompt, pv.schema_json, pv.generated_code, pv.quality_score, pv.created_by, pv.created_at
FROM page_versions pv
JOIN project_pages pp ON pp.id = pv.page_id
JOIN projects p ON p.id = pp.project_id
WHERE pv.id = $1 AND pv.page_id = $2 AND p.user_id = $3
`

type GetOwnedPageVersionParams struct {
	ID     pgtype.UUID
	PageID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetOwnedPageVersion(ctx context.Context, arg GetOwnedPageVersionParams) (PageVersion, error) {
	row := q.db.QueryRow(ctx, getOwnedPageVersion, arg.ID, arg.PageID, arg.UserID)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.Prompt,
		&i.SchemaJson,
		&i.GeneratedCode,
		&i.QualityScore,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnedPageVersions = `-- name: ListOwnedPageVersions :many
SELECT pv.id, pv.page_id, pv.version_number, pv.prompt, pv.schema_json, pv.generated_code, pv.quality_score, pv.created_by, pv.created_at
FROM page_versions pv
JOIN project_pages pp ON pp.id = pv.page_id
JOIN projects p ON p.id = pp.project_id
WHERE pv.page_id = $1 AND p.user_id = $2
ORDER BY pv.version_number DESC
`

type ListOwnedPageVersionsParams struct {
	PageID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) ListOwnedPageVersions(ctx context.Context, arg ListOwnedPageVersionsParams) ([]PageVersion, error) {
	rows, err := q.db.Query(ctx, listOwnedPageVersions, arg.PageID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageVersion
	for rows.Next() {
		var i PageVersion
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.VersionNumber,
			&i.Prompt,
			&i.SchemaJson,
			&i.GeneratedCode,
			&i.QualityScore,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVersionNumber = `-- name: NextVersionNumber :one
SELECT COALESCE(MAX(version_number), 0)::int + 1
FROM page_versions
WHERE page_id = $1
`

func (q *Queries) NextVersionNumber(ctx context.Context, pageID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNumber, pageID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
